<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fr.uha.ensisa.gl.testsquad</groupId>
    <artifactId>parent</artifactId>
    <version>0.0.4-Snapshot</version>
    <packaging>pom</packaging>

    <modules>
        <module>mantest-model</module>
        <module>mantest-dao-mem</module>
        <module>mantest-app</module>
        <module>mantest-aggregate</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
            <plugins>
                <!-- Maven default test plugin needs to be upgraded for JUnit 5 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.2</version>
                    <executions>
                        <execution>
                            <id>default-test</id>
                            <goals>
                                <goal>test</goal>
                            </goals>
                            <configuration>
                                <skip>${skip.tests}</skip>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${jacoco.version}</version>
                    <configuration>
                        <excludes>
                            <exclude>fr/uha/ensisa/gl/testsquad/config/*</exclude>
                        </excludes>
                    </configuration>
                    <executions>
                        <execution>
                            <id>default-prepare-agent</id>
                            <goals>
                                <goal>prepare-agent</goal>
                            </goals>
                            <configuration>
                                <skip>${skip.jacoco.prepare}</skip>
                            </configuration>
                        </execution>
                        <execution>
                            <id>default-report</id>
                            <goals>
                                <goal>report</goal>
                            </goals>
                            <configuration>
                                <skip>${skip.jacoco.report}</skip>
                            </configuration>
                        </execution>
                        <execution>
                            <id>default-check</id>
                            <goals>
                                <goal>check</goal>
                            </goals>
                            <configuration>
                                <skip>${skip.jacoco.check}</skip>
                                <rules>
                                    <rule>
                                        <element>BUNDLE</element>
                                        <limits>
                                            <limit>
                                                <counter>COMPLEXITY</counter>
                                                <value>COVEREDRATIO</value>
                                                <minimum>0.90</minimum>
                                            </limit>
                                        </limits>
                                    </rule>
                                </rules>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <version>${spotbugs.version}</version>
                    <configuration>
                        <skip>${skip.spotbugs}</skip>
                        <plugins>
                            <plugin>
                                <groupId>com.h3xstream.findsecbugs</groupId>
                                <artifactId>findsecbugs-plugin</artifactId>
                                <version>1.12.0</version>
                            </plugin>
                        </plugins>
                    </configuration>
                    <executions>
                        <execution>
                            <id>default-check</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.pitest</groupId>
                    <artifactId>pitest-maven</artifactId>
                    <version>${pitest.version}</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.pitest</groupId>
                            <artifactId>pitest-junit5-plugin</artifactId>
                            <version>1.2.1</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <id>mutation-testing</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>mutationCoverage</goal>
                            </goals>
                            <configuration>
                                <skip>${skip.pitest.mutation}</skip>
                            </configuration>
                        </execution>
                    </executions>
                    <configuration>
                        <exportLineCoverage>true</exportLineCoverage>
                        <outputFormats>
                            <format>XML</format>
                            <format>CSV</format>
                        </outputFormats>
                        <withHistory>true</withHistory>
                        <threads>4</threads>
                        <targetClasses>
                            <param>fr.uha.ensisa.gl.testsquad.mantest.*</param>
                        </targetClasses>
                        <targetTests>
                            <param>fr.uha.ensisa.gl.testsquad.mantest.*Test</param>
                        </targetTests>
                    </configuration>
                </plugin>

            </plugins>
    </build>

    <properties>
        <mantest.version>0.0.4-Snapshot</mantest.version>


        <skip.tests>false</skip.tests>
        <skip.integration>false</skip.integration>
        <skip.remoteIT>true</skip.remoteIT>
        <skip.jacoco.prepare>false</skip.jacoco.prepare>
        <skip.jacoco.report>false</skip.jacoco.report>
        <skip.jacoco.check>false</skip.jacoco.check>
        <skip.jacoco.aggregate>false</skip.jacoco.aggregate>
        <skip.pitest.mutation>false</skip.pitest.mutation>
        <skip.pitest.aggregate>false</skip.pitest.aggregate>
        <skip.spotbugs>false</skip.spotbugs>
        <skip.ecobench>true</skip.ecobench>

        <junit.version>5.10.1</junit.version>
        <mockito.version>5.11.0</mockito.version>
        <jacoco.version>0.8.12</jacoco.version>
        <pitest.version>1.17.4</pitest.version>
        <spotbugs.version>4.8.6.0</spotbugs.version>

        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>